name: 'Docker Publish'

on:
  push:
    tags:
      - '*.*.*'

permissions:
  packages: write

jobs:
  publish-stable:
    name: Docker Publish

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: |
            ghcr.io/bhunter234/rclone-backup:latest
            ghcr.io/bhunter234/rclone-backup:${{ env.TAG }}